### PR TITLE
Class breakout

### PR DESCRIPTION
**Pull request by beavel**
I'm opening this pull request as a discussion as its a pretty drastic design change. Essentially, I broke out the constants, HTTP requests, and authentication into separate classes for easier maintenance/modification. This may violate the desire of keeping everything in one file for easier inclusion in other projects.

I did this work a while back to allow caching of credentials and to be able to prompt only when the token had expired. This enabled me to not have to store credentials anywhere in scripts and still update or set changes without needing to enter my password constantly. Below is a sample of how it could be used.

```php
<?php

require_once 'classes/autoload.php';

// Your Nest username and password.
$username = 'username@validdomain.com';

try {
    $nest = new Nest($username);
} catch (InvalidArgumentException $e) {
    <prompt for password>
    $nest = new Nest($username,$password);
}

// Get the device information:
$nest->getDeviceInfo();
$energyResults = $nest->getEnergyLatest();

?>
```

### CODE REVIEW

**Comment by gboudreau** [comment]
Indeed, the goal was easy inclusion, but since I include a Composer installation option, having many files is not that bad; composer takes care of installation.

**Comment by beavel** [comment]
Does that mean its something you are interested in pursuing or not? If yes, I'm sure there is probably a little clean up work need align namespace, etc. with project. Also, is there anything else you would want changed if moving forward with this type of implementation?

**Comment by gboudreau** [comment]
Yes, I would be interested.

Comments / requests:
- Please re-create this pull request by targeting by "v2" branch, instead of master. Since those changes are now backward compatible, I'd like to release them as a different major version.
- Please migrate the "regular" constants to class constants (in the Nest class). They really should have been from the start, and since we are already breaking backward compatibility, let's just refactor everything we need to at the same time.
- I saw you manually merged some commits I made in the past, since your original work started before I made/merged those changes, and a regular merge would not be possible. That is pretty dangerous; easy to miss a change and end up with a regression in the refactored code. I would suggest starting from the new "v2" branch, which is right now a copy of master, and re-do the class "explosion" from that codebase. That will ensure we're not missing anything in the resulting refactoring. And you can diff with this PR here to make sure you're not missing anything from your changes either.

**Comment by beavel** [comment]
Sounds good. I think I'm clear on points 1 & 3. I knew the manual merge was the wrong direction, but was the quickest way to start this conversation and see if the refactor was something that would be accepted before redoing the changes on latest.

As for point 2, what are you referring to when you say "regular" constants? I'm assuming this:

     const user_agent = 'Nest/2.1.3 CFNetwork/548.0.4';
     const protocol_version = 1;
     const login_url = 'https://home.nest.com/user/login';

Not sure if there was something else, or more you wanted to extract out into the constants.

It may be a few weeks before I can submit the new pull request, but I'll begin working on it as I have time.

**Comment by gboudreau** [comment]
Yes, class const. But I meant all those constants should become class const:
https://github.com/gboudreau/nest-api/pull/61/commits/4df74b1023f855319c951386b2a67bb0096ed80f

**Comment by gboudreau** [comment]
Deprecated. See #62

**Pull request closed without merging**
